---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: bnV0YW5peC80dQ==  # 'nutanix/4u'
  mysql-user: d3B1c2Vy                   # 'wpuser'
  mysql-password: d3BwYXNz               # 'wppass'